"""initial schema

Revision ID: 661f00ba6cc4
Revises: 
Create Date: 2026-09-07 16:26:45.009774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '661f00ba6cc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable PostGIS extension for geography types
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crops_code', 'crops', ['code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'EXTENSION_WORKER', 'OFFICIAL', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('diseases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('category', sa.Enum('DISEASE', 'PEST', 'NUTRIENT_DEFICIENCY', 'HEALTHY', name='disease_category'), nullable=False),
    sa.Column('severity_base', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='disease_severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id', 'code', name='uq_disease_crop_code')
    )
    op.create_index('ix_diseases_code', 'diseases', ['code'], unique=False)
    op.create_index('ix_diseases_crop_id', 'diseases', ['crop_id'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('area_unit', sa.String(length=10), nullable=False),
    sa.Column('primary_crop_id', sa.UUID(), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('irrigation_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_crop_id'], ['crops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_farms_location', 'farms', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_farms_primary_crop_id', 'farms', ['primary_crop_id'], unique=False)
    op.create_index(op.f('ix_farms_user_id'), 'farms', ['user_id'], unique=False)
    op.create_table('advisories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('immediate_actions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('monitoring', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('expert_consultation', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('input_guidance', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('preventive_measures', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_references', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_id', 'crop_id', 'language', 'version', name='uq_advisory_disease_crop_lang_ver')
    )
    op.create_index('ix_advisories_crop_id', 'advisories', ['crop_id'], unique=False)
    op.create_index('ix_advisories_disease_id', 'advisories', ['disease_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'CLOSED', name='case_status'), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_captured_at', 'cases', ['captured_at'], unique=False)
    op.create_index('ix_cases_crop_id', 'cases', ['crop_id'], unique=False)
    op.create_index('ix_cases_farm_id', 'cases', ['farm_id'], unique=False)
    op.create_index('ix_cases_farmer_id', 'cases', ['farmer_id'], unique=False)
    op.create_index('ix_cases_location', 'cases', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_cases_status', 'cases', ['status'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('all_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_case_id', 'predictions', ['case_id'], unique=False)
    op.create_index('ix_predictions_disease_id', 'predictions', ['disease_id'], unique=False)
    op.create_index('ix_predictions_is_primary', 'predictions', ['is_primary'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('extension_worker_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CONFIRMED', 'CORRECTED', name='verification_action'), nullable=False),
    sa.Column('corrected_disease_id', sa.UUID(), nullable=True),
    sa.Column('confidence_agreement', sa.Enum('AGREE', 'DISAGREE', 'UNCERTAIN', name='confidence_agreement'), nullable=True),
    sa.Column('field_observations', sa.Text(), nullable=True),
    sa.Column('field_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_before', sa.String(), nullable=False),
    sa.Column('status_after', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corrected_disease_id'], ['diseases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extension_worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_verification_case_id')
    )
    op.create_index(op.f('ix_verifications_action'), 'verifications', ['action'], unique=False)
    op.create_index(op.f('ix_verifications_case_id'), 'verifications', ['case_id'], unique=True)
    op.create_index(op.f('ix_verifications_extension_worker_id'), 'verifications', ['extension_worker_id'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_percent', sa.Integer(), nullable=True),
    sa.Column('rainfall_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.Column('forecast_3day', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_weather_snapshot_case_id')
    )
    op.create_index('ix_weather_snapshots_case_id', 'weather_snapshots', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_snapshots_case_id', table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_verifications_extension_worker_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_case_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_action'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index('ix_predictions_is_primary', table_name='predictions')
    op.drop_index('ix_predictions_disease_id', table_name='predictions')
    op.drop_index('ix_predictions_case_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_cases_status', table_name='cases')
    op.drop_index('ix_cases_location', table_name='cases', postgresql_using='gist')
    op.drop_index('ix_cases_farmer_id', table_name='cases')
    op.drop_index('ix_cases_farm_id', table_name='cases')
    op.drop_index('ix_cases_crop_id', table_name='cases')
    op.drop_index('ix_cases_captured_at', table_name='cases')
    op.drop_index('idx_cases_location', table_name='cases', postgresql_using='gist')
    op.drop_table('cases')
    op.drop_index('ix_advisories_disease_id', table_name='advisories')
    op.drop_index('ix_advisories_crop_id', table_name='advisories')
    op.drop_table('advisories')
    op.drop_index(op.f('ix_farms_user_id'), table_name='farms')
    op.drop_index('ix_farms_primary_crop_id', table_name='farms')
    op.drop_index('ix_farms_location', table_name='farms', postgresql_using='gist')
    op.drop_index('idx_farms_location', table_name='farms', postgresql_using='gist')
    op.drop_table('farms')
    op.drop_index('ix_diseases_crop_id', table_name='diseases')
    op.drop_index('ix_diseases_code', table_name='diseases')
    op.drop_table('diseases')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_crops_code', table_name='crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
